"""initial schema

Revision ID: f6e570bbd592
Revises: 
Create Date: 2026-09-29 13:43:06.012597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e570bbd592'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('inventory_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variety', sa.String(length=20), nullable=False),
    sa.Column('color_stage', sa.String(length=5), nullable=False),
    sa.Column('sacks_received', sa.Float(), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=False),
    sa.Column('sold_out', sa.Boolean(), nullable=False),
    sa.Column('logged_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_number', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('contact_info', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('manager_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_number', 'business_date', name='uq_order_display_per_day')
    )
    op.create_table('queue_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('applied_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sack_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('service', sa.String(length=15), nullable=False),
    sa.Column('color_stage', sa.String(length=5), nullable=False),
    sa.Column('variety_1', sa.String(length=20), nullable=False),
    sa.Column('variety_2', sa.String(length=20), nullable=True),
    sa.Column('addon_note', sa.String(length=255), nullable=True),
    sa.Column('queue_sequence', sa.Integer(), nullable=True),
    sa.Column('sack_status', sa.String(length=10), nullable=False),
    sa.Column('estimated_finish_at', sa.DateTime(), nullable=True),
    sa.Column('actual_finish_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sack_items')
    op.drop_table('queue_adjustments')
    op.drop_table('orders')
    op.drop_table('inventory_receipts')
    op.drop_table('users')
    op.drop_table('seasons')
    # ### end Alembic commands ###
